### ISSUE TITLE
iOS/Chrome issues

### ISSUE THREAD

**Issue by zaccety** [guidobouman/panelsnap#109]
Ace plugin, but I'm having trouble with it not working on iOS with Chrome (OK on Safari).

It won't scroll, just bounces back to the first section, don't suppose anyone has encountered this...

**Comment by guidobouman** [comment]
That's weird as they both should be powered by the same rendering engine: `Safari WebKit`. It's flagged though. Will pick this up sometime. Thanks for reporting!

**Comment by guidobouman** [comment]
Update: This happens when the Chrome address bar shows or hides, based on the direction you're scrolling. This directly conflicts with the plugin scrolling behaviour.

**Comment by guidobouman** [comment]
I just tested this again on the latest version of Chrome for iOS. This is not an issue anymore since the rewrite of v1.0.0. 🎉

**Comment by guidobouman** [comment]
The latest release is available on:
- [npm package](https://www.npmjs.com/package/panelsnap)
- [GitHub release](https://github.com/guidobouman/panelsnap/releases)
