### ISSUE TITLE
Container inside react component

### ISSUE THREAD

**Issue by BKengagement** [guidobouman/panelsnap#138]
I am having a hard time with the container option. Could you please assist in helping me create a container? Not all my section will need to have a snap option. 

componentDidMount() {
    const node = ReactDOM.findDOMNode(this);
    this.panelSnapInstance = new PanelSnap({
      container: node,
      panelSelector: '.panel'
    });
  }

**Comment by guidobouman** [comment]
Is your DOM node a scrolling div?

**Comment by BKengagement** [comment]
Yes I have the overflow as scroll. I am not getting any errors so it is finding the container. The scroll logic just doesn't work.

**Comment by BKengagement** [comment]
Ok, I got it to work with overflow:auto, and container height 100vh. The problem now is there are 2 scrollbars.  I am trying to achieve something like this. https://ueno.co/careers#new-york-city

**Comment by guidobouman** [comment]
I really like that idea!

Do you have a demo page I can look at?

**Comment by BKengagement** [comment]
https://codesandbox.io/embed/yjo5y0mvlx

**Comment by guidobouman** [comment]
That's a bit of a small demo. Anything with you code in there already? Do you have content before the panels like the inspiration page you shared?

**Comment by BKengagement** [comment]
Yes if you look at the component there are sections before and after. The app works just as the link, the snap functionality doesn't work.

**Comment by BKengagement** [comment]
If I set the container to body the panel snap works until all section leave the screen. If I set the container to a specific div then it breaks.

**Comment by BKengagement** [comment]
<iframe src="https://codesandbox.io/embed/yjo5y0mvlx" style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>

**Comment by BKengagement** [comment]
So is in not possible to have non snap-able section when the container is the body? Could really use your help...

**Comment by BKengagement** [comment]
All good, just had to rework your code. thx

**Comment by guidobouman** [comment]
Just wondering: what did you change? Changing the internals of a library is usually not a great idea. But is this something that should be in the library by default?

**Comment by guidobouman** [comment]
And I see your case: you want to be able to scroll freely when there are no containers in the viewport.
