### ISSUE TITLE
Add a method to destroy a PanelSnap instance

### ISSUE THREAD

**Issue by sampsonpete** [guidobouman/panelsnap#139]
My site uses [Barba.js views](http://barbajs.org/) for smooth transitions. Only one view requires panelsnap so I need to be able to destroy the instance when leaving that view. Otherwise, I’m left with errors saying ‘PanelSnap could not find a snappable panel’.

I can’t find any reference to this in the docs now. It looks like it used to exist in an older version, though: [How to use the destroy method?](https://github.com/guidobouman/panelsnap/issues/89), [How to detach panelsnap?](https://github.com/guidobouman/panelsnap/issues/44). 

Could you let me know if it’s possible in the latest version?

**Comment by hh83917** [comment]
```this.panelSnapInstance.off('activatePanel')```?

**Comment by sampsonpete** [comment]
Thanks, but I believe that the off() method is used to unsubscribe one of your own functions based on a panelsnap event. Rather than to turn off panelsnap itself.

@guidobouman how can I destroy a panelsnap instance to prevent errors when moving to a page with no panels?

**Comment by guidobouman** [comment]
@sampsonpete  There are undocumented `disable()` & `enable()` methods to pause and resume PanelSnap. There's no `destroy` method right now.

You could try removing the panelSnap instance (`instance = null; delete instance;`), but that would rely on garbage collection, not removing the actual event listeners.

**Comment by guidobouman** [comment]
Great point though! As panelSnap should provide a way to destroy itself when an app loads another page.
