### ISSUE TITLE
Add / remove Class on snapStart snapStop

### ISSUE THREAD

**Issue by ineedholidays** [guidobouman/panelsnap#142]
Hi,
I've made the plugin work in basic mode with options:
```
 document.addEventListener("DOMContentLoaded", function() {
  var options = {
    container: document.body,
    panelSelector: '.snapp',
    directionThreshold: 100,
    delay: 0,
    duration: 300,
  };

  new PanelSnap(options);
          });
```

I'm trying to add an active class to current panel but not really sure about how this works, and I haven't found it in the examples:

on([string] eventName, [function] callbackFunction(panel))
 
What's the way to call functions on snapStart / snapStop... ?

Thank you in advance
Best,
R

**Comment by guidobouman** [comment]
You've found the right API method. It calls the callback with the relevant panel DOM element as the first parameter.

This is the way you can achieve your goal:

```
var panelSnapInstance = new PanelSnap(options);
panelSnapInstance.on('activatePanel', function(panel) {
  document.querySelector('.snapp.active').classList.remove('active');
  panel.classList.add('active');
});
```
